### ISSUE TITLE
ant build fails

### ISSUE THREAD

**Issue by strophi** [TYPO3-Solr/nutch-typo3-cms#5]
Hi, 

I've tried to build on Ubuntu 16.04 Server LTS. But ant throws an error. Would you please give me a hint whats going wrong?

thanks in advance, 

Jan

Buildfile: /home/xyz/Downloads/nutch-typo3-cms-master/build.xml

init:
    [mkdir] Created dir: /home/xyz/Downloads/nutch-typo3-cms-master/build
    [mkdir] Created dir: /home/xyz/Downloads/nutch-typo3-cms-master/build/nutch
    [mkdir] Created dir: /home/xyz/Downloads/nutch-typo3-cms-master/build/dist

compile-checkout-src:
     [exec] A    build/nutch/lib
     [exec] A    build/nutch/lib/native
     [exec] A    build/nutch/ivy
     [exec] A    build/nutch/src
     [exec] A    build/nutch/src/plugin
     [exec] A    build/nutch/src/plugin/index-more
     [exec] A    build/nutch/src/plugin/index-more/src
     [exec] A    build/nutch/src/plugin/index-more/src/test
     [exec] A    build/nutch/src/plugin/index-more/src/test/org
     [exec] A    build/nutch/src/plugin/index-more/src/test/org/apache
     [exec] A    build/nutch/src/plugin/index-more/src/test/org/apache/nutch
     [exec] A    build/nutch/src/plugin/index-more/src/test/org/apache/nutch/indexer
     [exec] A    build/nutch/src/plugin/index-more/src/test/org/apache/nutch/indexer/more
     [exec] A    build/nutch/src/plugin/index-more/src/java
     [exec] A    build/nutch/src/plugin/index-more/src/java/org
     [exec] A    build/nutch/src/plugin/index-more/src/java/org/apache
     [exec] A    build/nutch/src/plugin/index-more/src/java/org/apache/nutch
     [exec] A    build/nutch/src/plugin/index-more/src/java/org/apache/nutch/indexer
     [exec] A    build/nutch/src/plugin/index-more/src/java/org/apache/nutch/indexer/more
     [exec] A    build/nutch/src/plugin/parse-ext
     [exec] A    build/nutch/src/plugin/parse-ext/src
     [exec] A    build/nutch/src/plugin/parse-ext/src/test
     [exec] A    build/nutch/src/plugin/parse-ext/src/test/org
     [exec] A    build/nutch/src/plugin/parse-ext/src/test/org/apache
     [exec] A    build/nutch/src/plugin/parse-ext/src/test/org/apache/nutch
     [exec] A    build/nutch/src/plugin/parse-ext/src/test/org/apache/nutch/parse
     [exec] A    build/nutch/src/plugin/parse-ext/src/test/org/apache/nutch/parse/ext
     [exec] A    build/nutch/src/plugin/parse-ext/src/java
     [exec] A    build/nutch/src/plugin/parse-ext/src/java/org
     [exec] A    build/nutch/src/plugin/parse-ext/src/java/org/apache
     [exec] A    build/nutch/src/plugin/parse-ext/src/java/org/apache/nutch
     [exec] A    build/nutch/src/plugin/parse-ext/src/java/org/apache/nutch/parse
     [exec] A    build/nutch/src/plugin/parse-ext/src/java/org/apache/nutch/parse/ext
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org/apache
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org/apache/nutch
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org/apache/nutch/net
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org/apache/nutch/net/urlnormalizer
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/test/org/apache/nutch/net/urlnormalizer/pass
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org/apache
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org/apache/nutch
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org/apache/nutch/net
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org/apache/nutch/net/urlnormalizer
     [exec] A    build/nutch/src/plugin/urlnormalizer-pass/src/java/org/apache/nutch/net/urlnormalizer/pass
     [exec] A    build/nutch/src/plugin/parse-html
     [exec] A    build/nutch/src/plugin/parse-html/src
     [exec] A    build/nutch/src/plugin/parse-html/src/test
     [exec] A    build/nutch/src/plugin/parse-html/src/test/org
     [exec] A    build/nutch/src/plugin/parse-html/src/test/org/apache
     [exec] A    build/nutch/src/plugin/parse-html/src/test/org/apache/nutch
     [exec] A    build/nutch/src/plugin/parse-html/src/test/org/apache/nutch/parse
     [exec] A    build/nutch/src/plugin/parse-html/src/test/org/apache/nutch/parse/html
     [exec] A    build/nutch/src/plugin/parse-html/src/java
     [exec] A    build/nutch/src/plugin/parse-html/src/java/org
     [exec] A    build/nutch/src/plugin/parse-html/src/java/org/apache
     [exec] A    build/nutch/src/plugin/parse-html/src/java/org/apache/nutch
     [exec] A    build/nutch/src/plugin/parse-html/src/java/org/apache/nutch/parse
     [exec] A    build/nutch/src/plugin/parse-html/src/java/org/apache/nutch/parse/html
     [exec] A    build/nutch/src/plugin/protocol-httpclient
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org/apache
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org/apache/nutch
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient
     [exec] A    build/nutch/src/plugin/parse-html/ivy.xml
     [exec] A    build/nutch/src/plugin/parse-html/plugin.xml
     [exec] A    build/nutch/CHANGES.txt
     [exec] A    build/nutch/src/plugin/protocol-httpclient/src/java/org/apache/nutch/protocol/httpclient/Http.java
     [exec] svn: E200014: Checksum mismatch for '/home/siepmannj/Downloads/nutch-typo3-cms-master/build/nutch/lib/native/README.txt':
     [exec]    expected:  2c629b324b2e63e16b28d635ae1e384a
     [exec]      actual:  2703395cb677b36bbe04f0e868a10d2b
     [exec] 
     [exec] Result: 1

compile-patch-nutch:
    [patch] can't find file to patch at input line 5
    [patch] Perhaps you used the wrong -p or --strip option?
    [patch] The text leading up to this was:
    [patch] --------------------------
    [patch] |Index: conf/nutch-default.xml
    [patch] |===================================================================
    [patch] |--- conf/nutch-default.xml	(Revision 1380217)
    [patch] |+++ conf/nutch-default.xml	(Arbeitskopie)
    [patch] --------------------------
    [patch] File to patch: 
    [patch] Skip this patch? [y] 
    [patch] Skipping patch.
    [patch] 1 out of 1 hunk ignored
    [patch] can't find file to patch at input line 39
    [patch] Perhaps you used the wrong -p or --strip option?
    [patch] The text leading up to this was:
    [patch] --------------------------
    [patch] |Index: src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HtmlParser.java
    [patch] |===================================================================
    [patch] |--- src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HtmlParser.java	(Revision 1380217)
    [patch] |+++ src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HtmlParser.java	(Arbeitskopie)
    [patch] --------------------------
    [patch] File to patch: 
    [patch] Skip this patch? [y] 
    [patch] Skipping patch.
    [patch] 6 out of 6 hunks ignored

BUILD FAILED
/home/xyz/Downloads/nutch-typo3-cms-master/build.xml:59: 'patch' failed with exit code 1

Total time: 26 seconds

**Comment by dkd-dobberkau** [comment]
Please use the released Versions: https://github.com/dkd/nutch-typo3-cms/releases
Be aware that we are currently not maintaining Apachen Nutch for the moment.

**Comment by dkdlniazman** [comment]
Hi Jan,

as the build.xml has been updated recently in our [2.2.0 release](https://github.com/TYPO3-Solr/nutch-typo3-cms/releases/tag/2.2.0), this issue should be fixed. 

Thanks and greetings
Lmar
