### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fedir** [TYPO3-Solr/nutch-typo3-cms#6]
Hi there !
I would like to ask, if the project is still maintained ?
TYPO3 7 ? TYPO3 8 ?
Support of newer Solr versions ?
New versions of Nutch ?
Thank You very much for Your answer.
Best regards,
Fedir

**Comment by dkd-dobberkau** [comment]
Hi Fedir. We have not decided yet. But we would accept PR for sure. Greetings, Olivier
